### ISSUE TITLE
SocioMark Logo

### ISSUE THREAD

**Issue by bodhisha** [MLH-Fellowship/SocioMark#100]
- Logo for SocioMark

**Comment by bodhisha** [comment]
White Logo
![SocioMarkLogo](https://user-images.githubusercontent.com/34866653/114220775-0bf3dd80-998a-11eb-9707-ce25e0991a88.png)
Black Logo
![LogoBlack](https://user-images.githubusercontent.com/34866653/114220820-1a41f980-998a-11eb-91f5-9b14abde98d7.png)
Black Logo with White Background:
![WhiteBG](https://user-images.githubusercontent.com/43996118/115142703-cb1e5780-a060-11eb-8d85-79b35ee889a2.png)

**Comment by DebugAgrawal** [comment]
Frontpage 
![frontpage](https://user-images.githubusercontent.com/64848982/114246636-b8e15100-99b0-11eb-8cad-177589b2dd18.png)

Verification
![authenticate](https://user-images.githubusercontent.com/64848982/114246722-f1812a80-99b0-11eb-8d79-705978fc712f.png)
