### ISSUE TITLE
Report threshold 

### ISSUE THREAD

**Issue by bodhisha** [MLH-Fellowship/SocioMark#107]
Return the post only if the number of reports < threshold

**Comment by amalaabraham** [comment]
@bodhisha hey, I can take up this issue. :) Also, Lemme know about the threshold you are referring to!

**Comment by aitikgupta** [comment]
@amalaabraham 
It can be any threshold. Basically, currently we call `<backend_url>/post/all` to get _all_ the posts in the database - we need to return back only those posts whose `post.report_counter < 5`, where `5` is just a threshold (it is up for discussion as to what that exact value should be).

**Comment by amalaabraham** [comment]
Makes sense! May be I can add threshold in an env variable so the developer can change if he wants. @aitikgupta

**Comment by aitikgupta** [comment]
@amalaabraham that's right :D

See https://github.com/MLH-Fellowship/SocioMark/blob/main/backend/.env.example for the variables we currently use. 👍🏼

**Comment by amalaabraham** [comment]
Sure :)
