### ISSUE TITLE
Reset placeholder text 

### ISSUE THREAD

**Issue by bodhisha** [MLH-Fellowship/SocioMark#109]
Placeholder text needs to be reset every time the user submits the form (Applicable for every input in frontend)

**Comment by MyrrhDev** [comment]
Hey there @bodhisha ! I can work on this issue.

**Comment by bodhisha** [comment]
@MyrrhDev  Hey, thanks for checking this out! You can work on it.. Feel free to reach out if you have got any doubts. 🎉🚀

**Comment by MyrrhDev** [comment]
thanks! :) I'm just getting it all set up, so just wondering if you mean a particular form when you say "the form", or *any* form (?)

**Comment by bodhisha** [comment]
So we have forms/input fields for `login` , `register` , `search`,  `Add posts` etc. On submission, the value in the fields should be cleared and should be back to ""
