### ISSUE TITLE
Show Verification's User as a link

### ISSUE THREAD

**Issue by aitikgupta** [MLH-Fellowship/SocioMark#112]
Currently, the return was verification contains the `user_id`, `name` and `email_id`.

We just need to covert:
https://github.com/MLH-Fellowship/SocioMark/blob/39eb2f05a1a2da1ca6f6dfee388474da737c6a57/frontend/src/Components/Post/Post.js#L138-L147

Into a link `/user/{user_id}`

**Comment by MyrrhDev** [comment]
Hey! I think I can do this one :)
