### ISSUE TITLE
Website Description

### ISSUE THREAD

**Issue by aitikgupta** [MLH-Fellowship/SocioMark#114]
Found while sending SocioMark's link on Discord.

![image](https://user-images.githubusercontent.com/43996118/114738773-e8ec7380-9d65-11eb-828a-07f269ce6540.png)

We can change the description to the one mentioned in the `About` section of this repository.

**Comment by dp46504** [comment]
in /frontend/public/index.html you can change line 13 and that should do the work ;)
![image](https://user-images.githubusercontent.com/59868006/114763737-7084b300-9d63-11eb-8622-eebc14b839e0.png)

**Comment by aitikgupta** [comment]
Hey @dp46504, browny points for creating a PR out of this! :p
Do you wanna be assigned?

**Comment by aitikgupta** [comment]
Hey @dp46504, thanks for the insight. You'll get browny points for creating a PR out of this! :p
Do you wanna be assigned?

**Comment by dp46504** [comment]
I'm starting to contributing but I have some issues with learning it. But on frontend i have issues running npm start on windows. Changing npm start script to SET NODE_ENV=development craco start didn't do much. I'm new at this :/

**Comment by aitikgupta** [comment]
@dp46504 thanks for reporting this, the error is coming from our side, basically we did things very fast on our Linux machines, without worrying about Windows users. Can you open a separate issue where we can discuss the solution to this?

**Comment by aitikgupta** [comment]
@dp46504 the errors must be resolved now!
Now you would be able to run the backend, as well as the frontend. :D

**Comment by dp46504** [comment]
I will try it later ;)
