### ISSUE TITLE
Threshold type from config

### ISSUE THREAD

**Issue by MyrrhDev** [MLH-Fellowship/SocioMark#142]
Bug in threshold from config
i.e.:
async def retrieve_post(post_id: str) -> dict:
    post = await posts_collection.find_one({"_id": ObjectId(post_id)})
    if post and (post["report_counter"] <= int(config["THRESHOLD"])):
        user = await users_collection.find_one({"_id": post["user_id"]})

You need to force the "int()" on that otherwise it raises a "comparison error int and string" and does not load any posts

**Comment by aitikgupta** [comment]
This is coming from https://github.com/MLH-Fellowship/SocioMark/pull/136

I'm assigning you for a bugfix!

**Comment by aitikgupta** [comment]
closed via https://github.com/MLH-Fellowship/SocioMark/pull/143
