### ISSUE TITLE
Remove Post ID from User's Posts

### ISSUE THREAD

**Issue by aitikgupta** [MLH-Fellowship/SocioMark#22]
`/post/delete` only deletes the instance from `posts_collection`, it should also remove it's unique id from user's posts (list of unique ids)

**Comment by bodhisha** [comment]
@aitikgupta  Actually, is that really needed to store the unique id of posts in the users' table

- We are storing both user_id and post_id in posts_collection
- We can get all the posts by a particular user from posts_collection itself
- This will ensure that data is not duplicated

**Comment by aitikgupta** [comment]
@bodhisha That makes sense, similar argument can be made for storing the unique id of likes in the posts' table

We _can_ divide our /posts API in a way that 2 calls will have to be made for a single post. (Actually 3)

1. To get all the data we get from a post right now
2. To get all the likes on that post (call on likes_collection with post_id = id)
3. To get all the comments on that post (call on comments_collection with post_id = id)

But from an end-user's perspective, the question is do we want 3 calls to get a single post? (I think Yes)

Let's say a user clicked on the Like button -> We will call the 2nd API to update the likes
Let's say a user commented -> We will call the 3rd API to update the comments
All other metadata like Image and Description and Author Name/Email -> We will call the 1st API
