### ISSUE TITLE
Update file Upload field in register API to Optional

### ISSUE THREAD

**Issue by bodhisha** [MLH-Fellowship/SocioMark#46]
- Currently its a required field

**Comment by aitikgupta** [comment]
Will be closed by https://github.com/Open-Sourced-Olaf/SocioMark/pull/45/commits/8178613e80e6ca133a20420659d00bd92d897a91 and https://github.com/Open-Sourced-Olaf/SocioMark/pull/45/commits/ce2c108b44175ebd8922850653e13f5d84ddec94.
