### ISSUE TITLE
Edit Post in Post.js

### ISSUE THREAD

**Issue by aitikgupta** [MLH-Fellowship/SocioMark#85]
One can edit their post's description, need frontend for that.

**Comment by suhanichawla** [comment]
@aitikgupta I'd like to work on this issue

**Comment by aitikgupta** [comment]
@suhanichawla sure, go ahead :)

The relevant entrypoint for frontend is- https://github.com/MLH-Fellowship/SocioMark/blob/39eb2f05a1a2da1ca6f6dfee388474da737c6a57/frontend/src/Components/Post/Post.js#L158

And for backend is - https://github.com/MLH-Fellowship/SocioMark/blob/39eb2f05a1a2da1ca6f6dfee388474da737c6a57/backend/app/server/routes/post.py#L39-L43

**Comment by aitikgupta** [comment]
Note that you will need to break down `updated_post` (see `UpdatePostModel`) to send a `description: str = Form(None)` from the frontend. See this for more information:
https://github.com/MLH-Fellowship/SocioMark/blob/39eb2f05a1a2da1ca6f6dfee388474da737c6a57/backend/app/server/models/post.py#L21-L29
